# See the structure in vars/structure-dat.yml

- assert:
    that: sample is defined
    fail_msg: The variable *sample* is mandatory. e.g. sample=04

- name: Create csv file from qc; HF QC
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
    content: |
      {% for v,f,ch,cl in vg|zip(fn)|zip(ch)|zip(cl)|map('flatten')|list %}
      {{ "%.4f" % v }};{{ "%.6f" % f }};{{ "%.6f" % ch }};{{ "%.6f" % cl }}
      {% endfor %}
  vars:
    fnorm: "{{ data.qc[sample].fnorm }}"
    a: "{{ (data.qc[sample].a_b_c_vg_cn_fn|map('split')|reverse)[:80] }}"
    vg: "{{ a|map(attribute='3')|map('float')|list }}"  # Gate volatge
    ch: "{{ a|map(attribute='4')|map('float')|list }}"  # HF C/Cox
    fn: "{{ a|map(attribute='5')|map('float')|list }}"  # Surface potential normalized
    cl: "{{ fn|eq_3_2(vg, fnorm|float) }}"              # LF C/Cox

- name: Create csv file from ql; LF
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-lf-{{ sample }}.csv"
    content: |
      {% for v,c in vg|zip(cn) %}
      {{ v }};{{ c }}
      {% endfor %}
  vars:
    a: "{{ (data.ql[sample].v_cn|map('split')|list)[:130] }}"
    vg: "{{ a|map(attribute='0')|list }}"
    cn: "{{ a|map(attribute='1')|list }}"

- name: Create gnuplot files for sample
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file_hfqc = "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
      file_lf = "{{ figure_dir }}/{{ figure }}-lf-{{ sample }}.csv"
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      # set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      set terminal epslatex color 10 size 5.5in,3.6in
      # set terminal pdf
      set datafile separator ";"
      set xrange [-2:6.0]
      set yrange [0.5:1.2]
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      plot file_hfqc u 1:3 w l t "${C}_{mos}^{HF}$" at end, \
                  '' u 1:4 w l t "${C}_{mos}^{LF}$" at end
      #    file_lf u 1:2 w l t "${C}_{mos}^{LF}$" at end
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'QC method'
        xlabel: 'Gate voltage ${V}_g$'
        ylabel: '${C}/{C}_{ox}$'
      sk:
        title: 'QC metóda'
        xlabel: 'Napätie hradla ${V}_g$'
        ylabel: '${C}/{C}_{ox}$'
