# See the structure in vars/structure-dat.yml

- assert:
    that: sample is defined
    fail_msg: The variable *sample* is mandatory. e.g. sample=04

- name: Create csv file from qc; High Frequency
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
    content: |
      {% for v,c,f in vg|zip(cn)|zip(fn)|map('flatten')|list %}
      {{ v }};{{ c }};{{ f }}
      {% endfor %}
  vars:
    a: "{{ (data.qc[sample].a_b_c_vg_cn_fn|map('split')|reverse)[:80] }}"
    vg: "{{ a|map(attribute='3')|list }}"
    cn: "{{ a|map(attribute='4')|list }}"
    fn: "{{ a|map(attribute='5')|list }}"

- name: Create gnuplot files for sample
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file_hf = "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
      #
      {% if terminal|d('eps') == 'pdf' %}
      set terminal pdf
      set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      {% else %}
      set terminal epslatex color 10 size 5.5in,3.9in
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      {% endif %}
      #
      set datafile separator ";"
      set xrange [-2:6.0]
      set yrange [0.5:1.2]
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      plot file_hf u 1:2 w l t "${C}_{mos}^{HF}$" at end, \
                '' u 1:3 w l t "${\\varphi}_{s}^{HF}$" at end
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'QC method'
        xlabel: 'Gate voltage ${V}_g$'
        ylabel: '${C}/{C}_{ox}$ \\qquad $(1-{\\varphi}/{\\varphi}_{norm})$'
      sk:
        title: 'QC metóda'
        xlabel: 'Napätie hradla ${V}_g$'
        ylabel: '${C}/{C}_{ox}$ \\qquad $(1-{\\varphi}/{\\varphi}_{norm})$'
