# See the structure in vars/structure-dat.yml 

- name: Create csv files from nxfile
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item.key }}.csv"
    content: |
      {% for x,y in w|zip(n) %}
      {{ x|float / 1e-6 }};{{ y }}
      {% endfor %}
  loop: "{{ data.nxfile|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  vars:
    a: "{{ item.value.w_n|map('split')|list }}"
    n: "{{ a|map(attribute='1')|list }}"
    w: "{{ a|map(attribute='0')|list }}"

- name: Create gnuplot files
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      # file = "{{ figure_dir }}/{{ figure }}.csv"
      #
      {% if terminal|d('eps') == 'pdf' %}
      set terminal pdf
      set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      {% else %}
      set terminal epslatex color 10 size 5.5in,3.9in
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      {% endif %}
      #
      set datafile separator ";"
      set xrange [0:0.8]
      set yrange [1e21:2e23]
      set logscale y 10
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      filelist=system("ls {{ figure_dir }}/{{ figure }}-*.csv")
      plot for [filename in filelist] filename with dots notitle
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'Dopant profile'
        xlabel: 'Depth $[\\mu{m}]$'
        ylabel: 'Concentration $[{m}^{-3}]$'
      sk:
        title: 'Kocentrácia dopantov'
        xlabel: 'Hĺbka $[\\mu{m}]$'
        ylabel: 'Koncentrácia $[{m}^{-3}]$'
