- name: Create csv file from data_other
  copy:
    dest: "{{ figure_dir }}/{{ figure }}.csv"
    content: |
      {% for x,y in w|zip(d) %}
      {{ "%.2f" % (x|float / 1e-6) }};{{ "%.6f" % (y|float) }}
      {% endfor %}
  vars:
    _file: "{{ data_other }}/{{ figure }}.csv"
    a: "{{ lookup('file', _file).splitlines()|map('split')|list }}"
    w: "{{ a|map(attribute='0')|list }}"
    d: "{{ a|map(attribute='1')|list }}"

- name: Create gnuplot files
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file = "{{ figure_dir }}/{{ figure }}.csv"
      #
      {% if terminal|d('eps') == 'pdf' %}
      set terminal pdf
      set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      {% else %}
      set terminal epslatex color 10 size 5.5in,3.9in
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      {% endif %}
      #
      set datafile separator ";"
      set xrange [0:1.1]
      set yrange [0.01:0.024]
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      plot file with points notitle
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'Constant width SCR method'
        xlabel: 'Depth $[\\mu m]$'
        ylabel: '${dV_g}/{dt} \\quad  [{Vs}^{-1}]$'
      sk:
        title: 'Metóda konštantnej šírky OPN.'
        xlabel: 'Hĺbka $[\\mu{m}]$'
        ylabel: '${dV_g}/{dt} \\quad  [{Vs}^{-1}]$'
