- name: Create gnuplot files
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file = "{{ figure_dir }}/{{ figure }}.csv"
      #
      {% if terminal|d('eps') == 'pdf' %}
      set terminal pdf
      set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      {% else %}
      set terminal epslatex color 10 size 5.5in,3.9in
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      {% endif %}
      #
      set datafile separator ";"
      set key autotitle columnhead
      #
      set xrange [92:105]
      set yrange [-1.7:-1.1]
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      plot file with points notitle
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'Flatband voltage / Oxide thickness'
        xlabel: 'Oxide thickness $[nm]$'
        ylabel: 'Flatband Voltage $[V]$'
      sk:
        title: 'Napätie vyrovnaných pásov / Hrúbka oxidu'
        xlabel: 'Hrúbka oxidu $[nm]$'
        ylabel: 'Napätie vyrovnaných pásov $[V]$'
