# See the structure in vars/structure-dat.yml

- assert:
    that: sample is defined
    fail_msg: The variable *sample* is mandatory. e.g. sample=04

- name: Create csv file from qcn; Deep Depletion
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-ddqc-{{ sample }}.csv"
    content: |
      {% for v,c,f in vg|zip(cn)|zip(fn)|map('flatten')|list %}
      {{ v }};{{ c }};{{ f }}
      {% endfor %}
  vars:
    a: "{{ data.qcn[sample].a_b_c_vg_cn_fn|map('split')|list }}"
    vg: "{{ a|map(attribute='3')|list }}"
    cn: "{{ a|map(attribute='4')|list }}"
    fn: "{{ a|map(attribute='5')|list }}"

- name: Create csv file from qc; High Frequency
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
    content: |
      {% for v,c,f in vg|zip(cn)|zip(fn)|map('flatten')|list %}
      {{ v }};{{ c }};{{ f }}
      {% endfor %}
  vars:
    a: "{{ data.qc[sample].a_b_c_vg_cn_fn|map('split')|list }}"
    vg: "{{ a|map(attribute='3')|list }}"
    cn: "{{ a|map(attribute='4')|list }}"
    fn: "{{ a|map(attribute='5')|list }}"

- name: Create gnuplot files for sample
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file_dd = "{{ figure_dir }}/{{ figure }}-ddqc-{{ sample }}.csv"
      file_hf = "{{ figure_dir }}/{{ figure }}-hfqc-{{ sample }}.csv"
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      # set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      set terminal epslatex color 10 size 5.5in,3.9in
      # set terminal pdf
      set datafile separator ";"
      # set key autotitle columnhead
      set xrange [-2:10]
      set yrange [0:1.2]
      # set xtics 0.0,0.2e-6,0.8e-6
      # set ytics 0.0,0.2e-6,0.8e-6
      # set logscale x 10
      # set logscale y 10
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      # filelist=system("ls {{ figure_dir }}/{{ figure }}-*.csv")
      # plot for [filename in filelist] filename with dots notitle
      plot file_dd u 1:2 w l t "${C}_{mos}^{DD}$" at end, \
                '' u 1:3 w l t "${\\varphi}_{s}^{DD}$" at end, \
           file_hf u 1:2 w l t "${C}_{mos}^{HF}$" at beginning, \
                '' u 1:3 w l t "${\\varphi}_{s}^{HF}$" at beginning
      # f(x) = a*x + b*x
      # fit f(x) file via a, b
      # plot f(x) dt 11
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'QC method'
        xlabel: 'Gate voltage ${V}_g$'
        ylabel: '${C}/{C}_{ox}$ \\qquad $(1-{\\varphi}/{\\varphi}_{norm})$'
      sk:
        title: 'QC metóda'
        xlabel: 'Napätie hradla ${V}_g$'
        ylabel: '${C}/{C}_{ox}$ \\qquad $(1-{\\varphi}/{\\varphi}_{norm})$'
