- name: Create gnuplot files
  copy:
    dest: "{{ figure_dir }}/{{ figure }}-{{ item }}.gnuplot"
    content: |
      file = "{{ figure_dir }}/{{ figure }}.csv"
      set output "{{ figure_dir }}/{{ figure }}-{{ item }}.tex"
      # set output '{{ figure_dir }}/{{ figure }}-{{ item }}.pdf'
      set terminal epslatex color 10 size 5.5in,3.9in
      # set terminal pdf
      set datafile separator ";"
      set key autotitle columnhead
      #
      set xrange [0:80]
      set yrange [0:60]
      # set xtics 0.0,0.2e-6,0.8e-6
      # set ytics 0.0,0.2e-6,0.8e-6
      set logscale x 10
      set logscale y 10
      set title "{{ text[item].title}}"
      set xlabel "{{ text[item].xlabel}}"
      set ylabel "{{ text[item].ylabel}}"
      plot file with points notitle
      f(x) = a*x + b*x
      fit f(x) file via a, b
      plot f(x) dt 11
  loop: [en, sk]
  vars:
    text:
      en:
        title: 'Dopant activation'
        xlabel: 'Implant Dose $D_{i}{10}^{15}[{m}^{-2}]$'
        ylabel: 'Activated ions ${10}^{15}[{m}^{-2}]$'
      sk:
        title: 'Aktivácia dopantov'
        xlabel: 'Implantačná dávka $D_{i}{10}^{15}[{m}^{-2}]$'
        ylabel: 'Aktivované ióny ${10}^{15}[{m}^{-2}]$'
